### ISSUE TITLE
Use consistent dtypes

### ISSUE THREAD

**Issue by fred3m** [fred3m/scarlet#106]
We are not guaranteed that users will always use the default double precision for the input images and the output model (eg. LSST uses single precision). Internally we occasionally use `numpy.zeros`, `numpy.ones`, and perhaps other functions that generate an array of type `np.float64`, which results in unnecessary casting operations and can even give output models of the wrong type.

We should go back through the code, make sure that we are always using the proper `dtype`, and add an assert to nearly all of our tests to make sure that we are getting the expected output types.

**Comment by pmelchior** [comment]
Agreed. I also came to this problem with my `RandomSource` code which doesn't even require an observation and thus has no way of know what the `dtype` is.

How about adding `dtype` to `Frame`?

**Comment by fred3m** [comment]
I think that's a good idea. We can have it default to `numpy.float64` since that is the numpy default.

**Comment by pmelchior** [comment]
`np.float32` should do and give us 2x memory
