### ISSUE TITLE
only call `grad` once in `Blend`

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#114]
[Our use of `grad`](https://github.com/fred3m/scarlet/blob/5482878cf7f0847abc4a0b29ee55d58fd2b82eac/scarlet/blend.py#L121) is inefficient because it's called during every iteration even though the backward gradient tree doesn't change at all. Store the gradient function at the first call of `_backward` and call that function every time from then on.

**Comment by fred3m** [comment]
You should just be able to set `self._grad = grad(self._loss, tuple(range(len(parameters))))` in `Blend.__init__`. Then just call `self._grad(*parameters)` in `self._backward`.
