### ISSUE TITLE
update example notebooks

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#36]

**Comment by fred3m** [comment]
In the docs branch I'm taking a different approach. The problem with having an examples folder is that they become outdated every time we make even minor API changes. Instead I am going to include the examples in the docs folder, which are executed every time we build the docs. Read-the-docs will build them every time we update the repo, so we can ensure that they are always executing correctly, and also includes them in the documentation.

**Comment by pmelchior** [comment]
Great!

**Comment by fred3m** [comment]
The examples are now available in the docs at http://scarlet.readthedocs.io/en/latest/.
