### ISSUE TITLE
replace TVx / TVy with LinearFilter gradients

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#51]
currently we use proxmins gradient implementation instead of the faster LinearFilters. simply using gradients should speed these up

**Comment by ritzvik** [comment]
Should I take this up? A little guidance would be helpful.

**Comment by pmelchior** [comment]
Hi Ritwik,

thanks for your interest in scarlet. We're in the middle of a considerable code re-organization. I would hold off on the issues until we can merge the latest changes because some will become obsolete.

**Comment by ritzvik** [comment]
> Hi Ritwik,
> 
> thanks for your interest in scarlet. We're in the middle of a considerable code re-organization. I would hold off on the issues until we can merge the latest changes because some will become obsolete.

Sure, thanks :)
