### ISSUE TITLE
Set flag when fit hasn't converged

### ISSUE THREAD

**Issue by sowmyakth** [fred3m/scarlet#60]
Currently there is only a warning printed by proxmin when the fit hasn't converged. It would be useful to set an internal flag in such cases.

**Comment by pmelchior** [comment]
This is a good idea. Doing it properly requires an update to `proxmin`, which currently doesn't inform if the optimizer has converged. That's an omission that we will remedy. Once that's in place, it'll be simple to report that flag.

**Comment by fred3m** [comment]
I don't think that proxmin needs an update, if the number of iterations is equal to `max_iter` then the solution didn't converge. That's the only check that `proxmin` currently does. While we could put a flag in proxmin to check for this I don't think there is a reason to. It's very rare that it would converge on exactly the last iteration.

**Comment by pmelchior** [comment]
That's the simple solution, yes. However, `proxmin` knows the current errors for every component, which might be useful to return. This would be much lighter than the full `traceback` and provide decent diagnostics. I prefer that solution, which would also allow to make the convergence test.

**Comment by pmelchior** [comment]
I fixed this with a `proxmin` update, which is thus required (v0.5.2)
