### ISSUE TITLE
Another few cases which fails to finish deblending

### ISSUE THREAD

**Issue by demax58484** [fred3m/scarlet#65]
About 1% of my images report a singular matrix error. However, I cannot notice any difference between those images and images that deblend successfully. Detailed bug report and the case are attached.
<img width="449" alt="capture1" src="https://user-images.githubusercontent.com/28079535/47237562-7f19cb80-d3ad-11e8-9a29-19cf83afea1e.PNG">
[err.zip](https://github.com/fred3m/scarlet/files/2496984/err.zip)

**Comment by pmelchior** [comment]
It may not look like it, but I think this is related to the unstable behavior in #56 

We're investigating
