### ISSUE TITLE
Include issues in operators_pybind11.cc

### ISSUE THREAD

**Issue by herjy** [fred3m/scarlet#66]
When installing scalet with python2.7, the installation crashes as shown below. 
This is fixed easily by either replacing the <> by "" in the include lines, or by installing with python3.

```
joseph:scarlet remy$ sudo python2.7 setup.py install
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py:406: UserWarning: The version specified (u'0.3.b34b32b') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing requirements to scarlet.egg-info/requires.txt
writing scarlet.egg-info/PKG-INFO
writing top-level names to scarlet.egg-info/top_level.txt
writing dependency_links to scarlet.egg-info/dependency_links.txt
reading manifest file 'scarlet.egg-info/SOURCES.txt'
writing manifest file 'scarlet.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-x86_64/egg
running install_lib
running build_py
running build_ext
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /tmp/tmpTW9gRr.cpp -o tmp/tmpTW9gRr.o -std=c++14
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /tmp/tmpkRvneG.cpp -o tmp/tmpkRvneG.o -fvisibility=hidden
building 'scarlet.operators_pybind11' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iinclude -Iinclude -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peigen-0.0.9-py2.7.egg/peigen/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scarlet/operators_pybind11.cc -o build/temp.macosx-10.13-x86_64-2.7/scarlet/operators_pybind11.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="0.3.b34b32b" -std=c++14 -fvisibility=hidden
scarlet/operators_pybind11.cc:1:10: error: 'pybind11/pybind11.h' file not found with <angled> include; use "quotes" instead
#include <pybind11/pybind11.h>
         ^~~~~~~~~~~~~~~~~~~~~
         "pybind11/pybind11.h"
scarlet/operators_pybind11.cc:2:10: error: 'pybind11/numpy.h' file not found with <angled> include; use "quotes" instead
#include <pybind11/numpy.h>
         ^~~~~~~~~~~~~~~~~~
         "pybind11/numpy.h"
scarlet/operators_pybind11.cc:3:10: error: 'pybind11/stl.h' file not found with <angled> include; use "quotes" instead
#include <pybind11/stl.h>
         ^~~~~~~~~~~~~~~~
         "pybind11/stl.h"
scarlet/operators_pybind11.cc:4:10: error: 'pybind11/eigen.h' file not found with <angled> include; use "quotes" instead
#include <pybind11/eigen.h>
         ^~~~~~~~~~~~~~~~~~
         "pybind11/eigen.h"
scarlet/operators_pybind11.cc:72:1: warning: 'pybind11_init' is deprecated: PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE
      [-Wdeprecated-declarations]
PYBIND11_PLUGIN(operators_pybind11)
^
scarlet/pybind11/detail/common.h:261:20: note: expanded from macro 'PYBIND11_PLUGIN'
            return pybind11_init();                                            \
                   ^
scarlet/operators_pybind11.cc:72:1: note: 'pybind11_init' has been explicitly marked deprecated here
scarlet/pybind11/detail/common.h:256:5: note: expanded from macro 'PYBIND11_PLUGIN'
    PYBIND11_DEPRECATED("PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE")  \
    ^
scarlet/pybind11/detail/common.h:90:41: note: expanded from macro 'PYBIND11_DEPRECATED'
#  define PYBIND11_DEPRECATED(reason) [[deprecated(reason)]]
                                        ^
1 warning and 4 errors generated.
error: command '/usr/bin/clang' failed with exit status 1
```

**Comment by fred3m** [comment]
python 2.x is not supported by scarlet, as the majority of its dependencies no longer officially support python 2.

**Comment by herjy** [comment]
I am going to put this here because it seems related. I get this error when I try to install scarlet on OSX 10.14.2:

`remy$ sudo python3 setup.py install
/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:479: UserWarning: The version specified ('0.4.f259857') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
creating scarlet.egg-info
writing scarlet.egg-info/PKG-INFO
writing dependency_links to scarlet.egg-info/dependency_links.txt
writing requirements to scarlet.egg-info/requires.txt
writing top-level names to scarlet.egg-info/top_level.txt
writing manifest file 'scarlet.egg-info/SOURCES.txt'
reading manifest file 'scarlet.egg-info/SOURCES.txt'
writing manifest file 'scarlet.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/constraint.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/transformation.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/blend.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/config.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/resample.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/operator.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/cache.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/display.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/component.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/psf_match.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
copying scarlet/source.py -> build/lib.macosx-10.7-x86_64-3.7/scarlet
running build_ext
creating tmp
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.7m -c /tmp/tmpg3de0alw.cpp -o tmp/tmpg3de0alw.o -std=c++14
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
1 warning generated.
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.7m -c /tmp/tmpdn9hk55z.cpp -o tmp/tmpdn9hk55z.o -fvisibility=hidden
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
1 warning generated.
building 'scarlet.operators_pybind11' extension
creating build/temp.macosx-10.7-x86_64-3.7
creating build/temp.macosx-10.7-x86_64-3.7/scarlet
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.7m -I/Users/remy/.local/include/python3.7m -I/anaconda3/lib/python3.7/site-packages/peigen/include -I/anaconda3/include/python3.7m -c scarlet/operators_pybind11.cc -o build/temp.macosx-10.7-x86_64-3.7/scarlet/operators_pybind11.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="0.4.f259857" -std=c++14 -fvisibility=hidden
scarlet/operators_pybind11.cc:72:1: warning: 'pybind11_init' is deprecated: PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE
      [-Wdeprecated-declarations]
PYBIND11_PLUGIN(operators_pybind11)
^
/anaconda3/include/python3.7m/pybind11/detail/common.h:243:20: note: expanded from macro 'PYBIND11_PLUGIN'
            return pybind11_init();                                            \
                   ^
scarlet/operators_pybind11.cc:72:1: note: 'pybind11_init' has been explicitly marked deprecated here
/anaconda3/include/python3.7m/pybind11/detail/common.h:227:5: note: expanded from macro 'PYBIND11_PLUGIN'
    PYBIND11_DEPRECATED("PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE")  \
    ^
/anaconda3/include/python3.7m/pybind11/detail/common.h:90:41: note: expanded from macro 'PYBIND11_DEPRECATED'
#  define PYBIND11_DEPRECATED(reason) [[deprecated(reason)]]
                                        ^
1 warning generated.
g++ -bundle -undefined dynamic_lookup -L/anaconda3/lib -arch x86_64 -L/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/scarlet/operators_pybind11.o -o build/lib.macosx-10.7-x86_64-3.7/scarlet/operators_pybind11.cpython-37m-darwin.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1`
