### ISSUE TITLE
Flux-dependent operations in sources don't know about normalization

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#70]
So far, we've always assumed the A is normalized and the we get the flux of a component by summing of S. That's not necessarily true anymore. Problems arise e.g. here:
https://github.com/fred3m/scarlet/blob/master/scarlet/source.py#L62

We need to provide a per-component method, e.g. `get_flux()` that is aware of the normalization. This is a problem with the current scheme because the constraints are held by the components, but the normalization is held by the sources. Operationally both are constraints and should be treated equally, in which case both are held by the components. It's true that it's unlikely that someone would ever mix two components with different normalizations, but we've decided to retain that option.

So, this issue is for
* creating `Component.get_flux()`
* checking that we consistently call this method whenever the component flux is required.

This leaves one problem: what do we mean by flux? I argue it needs to be bolometric, i.e. `flux = morph.sum() * sed.sum()`. This form is -- yeah -- independent of normalization, which simplifies the problem considerably: components don't need to carry the normalization around at all.

Another issue will address the "normalization is a constraint problem".

**Comment by fred3m** [comment]
You make a good point. My only comment is that `get_flux` should not return a bolometric flux, but an array with the flux in each band, ie `flux=morph.sum() * sed`. The user can make it bolometric if they want, but this allows for more flexibility in cases (like the one you link to in your comment) where we want to weight sources by the flux in each band. We should also add `get_flux` to `Source`, where calling it returns the sum of `get_flux` for each component.
