### ISSUE TITLE
check if scipy is still needed

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#80]
with #78 a lot of functionality has been removed. `scipy` is only still used in two methods:
* `operator.prox_strict_monotonic`
* `psf_match.fit_target_psf`
If possible, it would be nice to remove the dependency

**Comment by pmelchior** [comment]
#86 has no `scipy` in its `setup.py`. I think that's an oversight because the two functions above do require `scipy`.

If so, add `scipy` to `setup.py` and close this issue.

**Comment by fred3m** [comment]
My take on it is that scipy is not a *required* dependency. It is not imported at the module level, but instead is imported inside those two functions. It is only used in `operator.prox_strict_monotonic` if the user chooses `use_nearest=True`, which is not recommended. It is also not necessary to use `fit_target_psf` to match the kernels, and in fact I don't usually use it any more. So the version of docs that I'm working on now lists `scipy` as an optional dependency, which I think is appropriate.
