### ISSUE TITLE
more than 3 filters for RGB images

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#85]

**Comment by pmelchior** [comment]
@fred3m The current implementation works well for 3-band, but isn't quite right for multiple bands or even if the bands have very different noise levels.

Here's the problem. Currently, the `Asinh` scaling is applied to `img`, and then a selection of the scaled bands is done to map onto RGB. It needs to be reversed: mapping B bands onto 3 RGB channels, followed by a scaling of the channels. The reason is that RGB constitutes a virtual filter set, so you first have to determine how you get from B filters to each of the RGB channels, then you can decide how to show this. Only in the last stage we are allowed to scale.

As a result, the current matplotlib-derived scaling isn't correct because you can feed it to any individual filter, as you have done in the [docs](https://scarlet.readthedocs.io/en/latest/user_docs.html#Display-functions), but for consistency it should only be applied once the RGB is formed. In other words, we should always insist that even single bands are converted to the corresponding RGB and then displayed.

I thus recommend to not base our norms on  `matplotlib.colors.Normalize`, so that folks don't confuse them with the optional argument of `matplotlib.imshow`. It also reduces the clutter in our code for e.g. the `inverse` function that isn't well-defined for multi-band images anyway. 

Agreed?

**Comment by fred3m** [comment]
I agree that the normalization is not done correctly here, but now that John Parejko added Roberts algorithm to astropy, and we already use astropy in the docs, we might as well just begin using that method instead. It fixes the problems that you state and I think will allow us to remove the `display` module entirely. I'll close this ticket once I have tested and updated all of the docs.

**Comment by pmelchior** [comment]
Can you point me to the astropy code?

**Comment by fred3m** [comment]
http://docs.astropy.org/en/stable/_modules/astropy/visualization/lupton_rgb.html#make_lupton_rgb

**Comment by pmelchior** [comment]
That's the trivial part of the algorithm. I have a full implementation, which includes the filter -> channel mapping, but I wanted to make sure that I'm not overseeing an aspect of `Normalize`.

Will commit my changes and PR soon

**Comment by fred3m** [comment]
Sounds good.
