### ISSUE TITLE
Scene should be renamed to `Frame`

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#90]
Scene is an ambiguous word, so it's better to clarify. 

In addition, I propose two changes
* `Blend` and `Observation` *have* `Frame` members instead of being derived from `Scene`
* `Blend.match()` happens during initialization to avoid ambiguity of who's responsible for calling it.

**Comment by fred3m** [comment]
This makes sense to me, except I'm not sure what you mean by `Blend.match`. `Blend` doesn't have a `match` method but calls `observation.match` for each observation it is passed.

**Comment by pmelchior** [comment]
Sorry, I misspoke. However, the match function should be called at init time given the metadata of Blend. This makes for a more logical way of specifying stuff for the users

**Comment by fred3m** [comment]
Isn't that what it does? https://github.com/fred3m/scarlet/blob/master/scarlet/blend.py#L25-L42

**Comment by pmelchior** [comment]
sure, this is merely to clarify the terminology. once done we need to update the docs, too.
