### ISSUE TITLE
AsinhNorm should have an additional stretch parameter

### ISSUE THREAD

**Issue by fred3m** [fred3m/scarlet#91]
`AsinhNorm` uses the algorithm from the Lupton et. al 2004 paper but does not include modifications to the algorithm included in the LSST stack and astropy that allow more control over the stretch. So the output using `AsinhNorm` is
<img width="358" alt="Screen Shot 2019-06-07 at 5 29 28 PM" src="https://user-images.githubusercontent.com/2251900/59134614-d45d1a00-8949-11e9-8738-d6a8fb6b8085.png">

while `make_lupton_rgb` can give a much more reasonable 
<img width="352" alt="Screen Shot 2019-06-07 at 5 29 35 PM" src="https://user-images.githubusercontent.com/2251900/59134645-eccd3480-8949-11e9-96a4-c892705a2586.png">

with the same `beta` by altering the stretch of the image.

We should either fix `AsinhNorm` or slightly adjust our classes so that we can use `make_lupton_rgb` from astropy in `channel_to_rgb`. Basically `Norm.call` would have to accept an argument list `*img` instead of an array of images.

My preference is to use `make_lupton_rgb` but if someone else wants to fix `AsinhNorm` I'm fine with that too.

**Comment by pmelchior** [comment]
The algorithm in the LSST stack is straightforward, but could you point me to some explanation for the modification. Also, did you use AsinhNorm or AsinhPercentileNorm?

**Comment by fred3m** [comment]
I haven't seen it documented anywhere, probably best to just ask Robert. I think that the basic idea is that the linear region can be stretched out, which is helpful for images with a lot of noise because it doesn't give as much intensity to the low flux regions.

**Comment by fred3m** [comment]
I'm just going to copy the display classes from astropy/LSST into scarlet for `Asinh` and `Linear` mappings and modify your `channels_to_rgb` to use the new scheme. I need this for the docs and it will avoid having to import from astropy in `scarlet.display`.

**Comment by pmelchior** [comment]
I'm not a fan of introducing another parameter if it has no method of setting it. Have you used `AsinhPercentileNorm` for the image above?

**Comment by fred3m** [comment]
The problem is that even `AsinhPercentileNorm` makes assumptions about how the user wants to display the data, namely it infers the `stretch` *and* `beta` from the percentiles, which can vary depending on the flux range of the image. Roberts algorithm is more robust and gives more control to the user. You can ask him directly, but I imagine that is why he updated the algorithm in the first place.

**Comment by pmelchior** [comment]
OK, add it as `AsinhStretchNorm`. We certainly don't need astropy for that bit of code

**Comment by fred3m** [comment]
I agree that we don't need to import astropy. But since this is already existing code from the LSST stack, why not just import `LinearMapping` and `AsinhMapping` as is? That way users familiar with the stack (and astropy) implementation will be able to use the same API and replace `AinhNorm` and `LinearNorm`? We can still implement the percentile classes and `rgb_to_channel` methods that you created to add to the existing features.

**Comment by fred3m** [comment]
Sorry, not `import`, I meant `copy` the classes into `scarlet.display`.

**Comment by pmelchior** [comment]
+1 for copying. Just keep the arguments and behavior the same, but call it something distinctive as I suggested before

**Comment by fred3m** [comment]
See https://github.com/fred3m/scarlet/commit/5e7bfdcd2149b471ff63b525b2d838f54c254637 for implementation. Same API for `AsinhPercentileNorm` and `LinearPercentileNorm` but now inheriting from the LSST `Mapping` class, which performs the functionality of `channels_to_rgb` internally, eliminating the need for the function.

**Comment by fred3m** [comment]
Usage examples:
```
norm = scarlet.display.AsinhMapping(minimum=images.min(), stretch=stretch, Q=Q)
img_rgb = scarlet.display.img_to_rgb(images, norm=norm)
```

or to use the linear by default

```
residual_rgb = scarlet.display.img_to_rgb(residual)
```

**Comment by pmelchior** [comment]
That's a massive change set for a tiny code contribution. Plus it calls things Mapping when they are norms.

**Comment by pmelchior** [comment]
Adressed in #92
