### ISSUE TITLE
linker failure from -lstdc++

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#97]
Attempting to install on my new Mac yields this:
```
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/scarlet
g++ -bundle -undefined dynamic_lookup -L/anaconda3/lib -arch x86_64 -L/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/scarlet/operators_pybind11.o -o build/lib.macosx-10.7-x86_64-3.7/scarlet/operators_pybind11.cpython-37m-darwin.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1
```

I have standard XCode, pybind11 from conda, and peigen from pip.

**Comment by fred3m** [comment]
This is related to #66 . We probably should have included the solution in the thread, namely that the problem is due to a change in OS X changing its C++ library. There is a work around that @herjy found, but I'm not sure where it is documented.

But we should also try to fix this more permanently to prevent the issue for future users.

**Comment by pmelchior** [comment]
Problem is that I don't see the `lstdc++` flags being set by us. This [Apple Release Note](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes?language=objc) explains the deprecation
> Building with libstdc++ was deprecated with Xcode 8 and is not supported in Xcode 10 when targeting iOS. C++ projects must now migrate to libc++ and are recommended to set a deployment target of macOS 10.9 or later, or iOS 7 or later. Besides changing the C++ Standard Library build setting, developers should audit hard-coded linker flags and target dependencies to remove references to libstdc++ (including -lstdc++, -lstdc++.6.0.9, libstdc++.6.0.9.tbd, and libstdc++.6.0.9.dylib). Project dependencies such as static archives that were built against libstdc++ will also need to be rebuilt against libc++. (40885260)

but I don't see what we need to update.

**Comment by herjy** [comment]
I think it was something about running an installer that should be on your machine but that is not executed by default, for like... reasons...
Try to run this and let me know:
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by fred3m** [comment]
try adding `-stdlib=libc++` when you run `setup.py`

**Comment by pmelchior** [comment]
@herjy good call. It's a big more elaborate, as explained [here](https://donatstudios.com/MojaveMissingHeaderFiles), but this solution is

```bash
xcode-select --install
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```
