### ISSUE TITLE
Create `RandomSource`

### ISSUE THREAD

**Issue by pmelchior** [fred3m/scarlet#98]
To test the importance of custom initialization, it is useful to have a source that has a randim uniform morphology, with a SED read of by projecting into the observation frames.

The first part is trivial, the second requires functionality that we might want to have anyways.

**Comment by herjy** [comment]
I'll look into that. MuSCADeT has random or 0 initialisation, which works because we don't optimise for the SED. But a good initialisation of the SEDs should do the trick too.
